# Regenerate the MQTT producer (mqttclient style) from the authoritative
# xreg manifest. The companion Kafka producer is regenerated by
# generate_producer.ps1.

. (Join-Path $PSScriptRoot "..\tools\require-xrcg.ps1")
Assert-XrcgVersion

xrcg generate `
    --style mqttclient `
    --language py `
    --definitions xreg\hongkong_epd.xreg.json `
    --endpoint HK.Gov.EPD.AQHI.Mqtt `
    --projectname hongkong_epd_mqtt_producer `
    --output hongkong_epd_mqtt_producer
