"""Idempotently (re)wire a Fabric Map item with Kusto-backed vector layers
for a freshly-deployed GTFS source.

A fresh ``gtfs/kql/gtfs.kql`` deployment lays down the following GTFS schema
in the target Eventhouse:

  * Bracketed, namespace-qualified base tables generated by avrotize a2k
    with ``--qualified-table-names --namespace GeneralTransitFeed``:
    ``['GeneralTransitFeed.VehiclePosition']``,
    ``['GeneralTransitFeed.TripUpdate']``,
    ``['GeneralTransitFeed.Alert']``,
    ``['GeneralTransitFeed.Routes']``, ``['GeneralTransitFeed.Stops']``,
    ``['GeneralTransitFeed.Trips']``, ``['GeneralTransitFeed.Shapes']``,
    ``['GeneralTransitFeed.Agency']``, plus the rest of the GTFS-Schedule
    entities, and the hand-authored derived flat tables
    ``['GeneralTransitFeed.VehiclePositionsFlat']`` and
    ``['GeneralTransitFeed.TripUpdateFlattened']``.
  * Per-table ``<X>Latest`` materialized views (also namespace-qualified)
    that pre-aggregate ``arg_max(___time, *) by ___type, ___source,
    ___subject`` so callers don't have to scan the full history every time
    they need the latest snapshot of a route, stop, trip, or shape.

This script wires the following layers (all parametrically generated against
those tables, no source-specific assumptions):

  1.  Route shapes (rail/subway/tram styling)
  2.  Bus route shapes (lighter weight, higher minZoom)
  3.  Live vehicles - bubbles (z12-16, coloured by route)
  4.  Live vehicles (detail) - bearing-oriented rectangles (z16+)
  5.  Major transit hubs
  6.  All stops - stratified to fit Fabric's 100k feature cap
  7.  Service alerts - alerts attached to specific stops (off by default)
  8.  Routes with active alerts - severity-coloured overlay on shape lines
  9.  Vehicle crowding (off by default)
  10. Vehicle data freshness grid (off by default)
  11. Delay heatmap (off by default)
  12. Arrival boards - three zoom-banded variants (tiny / compact / detail)
  13. Multi-modal stations - stops served by 2+ transit modes

The map's basemap centre + zoom are auto-discovered from the bounding box
of ``['GeneralTransitFeed.StopsLatest']`` so the script needs no source-specific tuning.

The Fabric Map item must already exist (see ``post-deploy.ps1`` which
auto-creates it). This script is idempotent: re-running drops the layers
it manages (matched by their KQL source's ``itemId`` binding) and recreates
them, so colour ramps, query changes, and viewport tweaks land cleanly.

Inputs (env vars or CLI args, mirroring ``dwd/fabric/wire_icond2_map.py``):

  FABRIC_WORKSPACE_ID   - GUID of the Fabric workspace containing the Map
  FABRIC_MAP_ID         - GUID of the Fabric Map item to patch
  FABRIC_KQL_DB_ID      - GUID of the KQL database with the GTFS tables
  KUSTO_CLUSTER_URI     - https://<cluster>.kusto.fabric.microsoft.com
  KUSTO_DB              - KQL database name (e.g. ``gtfs``)
  FABRIC_TOKEN          - bearer token for the Fabric REST API
  KUSTO_TOKEN           - bearer token for the Kusto cluster
  FABRIC_API_BASE       - override (default https://api.fabric.microsoft.com/v1)
"""
from __future__ import annotations

import argparse
import base64
import json
import os
import sys
import time
import uuid
from dataclasses import dataclass
from typing import Any, Optional

import requests


# ---------------------------------------------------------------------------
# Token + HTTP helpers (factored to match the dwd/pegelonline hook style).
# ---------------------------------------------------------------------------

def _get_token(env_name: str, scope: str) -> str:
    tok = os.environ.get(env_name)
    if tok:
        return tok.strip()
    try:
        from azure.identity import DefaultAzureCredential
    except ImportError as exc:
        raise SystemExit(
            f"{env_name} not set and azure-identity not installed; "
            f"either set {env_name} or `pip install azure-identity`."
        ) from exc
    return DefaultAzureCredential().get_token(scope).token


def _session(token: str) -> requests.Session:
    s = requests.Session()
    s.headers["Authorization"] = f"Bearer {token}"
    s.headers["Content-Type"] = "application/json"
    return s


def _poll_lro(session: requests.Session, response: requests.Response) -> Any:
    if response.status_code != 202:
        response.raise_for_status()
        return response.json() if response.content else None
    op_url = response.headers["Location"]
    while True:
        status = session.get(op_url).json()
        s = status.get("status")
        if s == "Succeeded":
            r = session.get(op_url + "/result")
            return r.json() if r.content else None
        if s == "Failed":
            raise RuntimeError(f"Fabric LRO failed: {json.dumps(status)[:600]}")
        time.sleep(2)


def _kql_mgmt(ks: requests.Session, kusto_uri: str, db: str, csl: str) -> dict[str, Any]:
    r = ks.post(f"{kusto_uri.rstrip('/')}/v1/rest/mgmt", json={"db": db, "csl": csl})
    if r.status_code >= 400:
        raise RuntimeError(f"KQL mgmt failed ({db}): HTTP {r.status_code} {r.text[:800]}")
    return r.json()


def _kql_query(ks: requests.Session, kusto_uri: str, db: str, csl: str) -> Optional[dict[str, Any]]:
    r = ks.post(f"{kusto_uri.rstrip('/')}/v2/rest/query", json={"db": db, "csl": csl})
    if r.status_code >= 400:
        raise RuntimeError(f"KQL query failed ({db}): HTTP {r.status_code} {r.text[:800]}")
    for frame in r.json():
        if (frame.get("FrameType") == "DataTable"
                and frame.get("TableKind") == "PrimaryResult"):
            return frame
    return None


# ---------------------------------------------------------------------------
# KQL helper functions installed in the target database.
# ---------------------------------------------------------------------------
#
# We lean on the materialized views (`['GeneralTransitFeed.RoutesLatest']`, `['GeneralTransitFeed.StopsLatest']`,
# `['GeneralTransitFeed.TripsLatest']`, `['GeneralTransitFeed.ShapesLatest']`) created by `gtfs.kql`. Each MV reduces a
# CloudEvents-shaped table down to one row per (___type, ___source,
# ___subject) - i.e. one row per logical GTFS entity per source. Reading the
# MV directly is constant-time regardless of how long the source has been
# ingesting, which is critical because a single Fabric Map render fans out
# to ~14 layer queries and each layer query may join multiple latest snapshots.
#
# For the streaming feeds (``['GeneralTransitFeed.Alert']``,
# ``['GeneralTransitFeed.TripUpdateFlattened']``,
# ``['GeneralTransitFeed.VehiclePositionsFlat']``) we time-bound by
# ``___time > ago(lookback)`` against the raw bracketed table.

GTFS_FUNCTIONS: list[str] = [
    # ------------------------------------------------------------------
    # Leaf helpers: take the per-source ``*Latest`` materialized views and
    # derive a stable display colour. These are wrapped as functions so the
    # rest of the pipeline doesn't have to know whether the upstream
    # `routeColor` field is populated or whether to fall back to a sensible
    # default per route_type.
    r'''
.create-or-alter function with (folder = "Map", skipvalidation = "true") gtfs_routes() {
    ['GeneralTransitFeed.RoutesLatest']
    | extend stroke_color = case(
        isnotempty(routeColor) and strlen(routeColor) == 6, strcat("#", routeColor),
        routeType == "SUBWAY", "#00A1DE",
        routeType == "RAIL",   "#6D6E71",
        routeType == "TRAM",   "#8E24AA",
        routeType == "BUS",    "#2E7D32",
        routeType == "FERRY",  "#00838F",
        routeType == "CABLE_CAR", "#795548",
        routeType == "GONDOLA",   "#5D4037",
        "#455A64")
    | project routeId, agencyId, routeShortName, routeLongName, routeType,
              routeColor, routeTextColor, stroke_color
}
''',
    r'''
.create-or-alter function with (folder = "Map", skipvalidation = "true") gtfs_stops() {
    ['GeneralTransitFeed.StopsLatest']
    | where isnotnull(stopLat) and isnotnull(stopLon)
    | project stopId, stopName, stopLat, stopLon, locationType, parentStation,
              platformCode, wheelchairBoarding
}
''',
    # ------------------------------------------------------------------
    # Map bounding box: queried once at deploy time so the basemap centre and
    # zoom auto-fit the source's geographic footprint. We deliberately read a
    # 1 % / 99 % quantile so a single mis-located stop in another country
    # doesn't pull the bounding box across continents.
    r'''
.create-or-alter function with (folder = "Map", skipvalidation = "true") gtfs_bbox() {
    gtfs_stops()
    | summarize lat_p01 = percentile(stopLat, 1), lat_p99 = percentile(stopLat, 99),
                lon_p01 = percentile(stopLon, 1), lon_p99 = percentile(stopLon, 99),
                cnt = count()
}
''',
    # ------------------------------------------------------------------
    # Route shape lines. Mid-detail polyline per shape, downsampled in two
    # bands: every 2nd point for bus shapes (frequent stops, low jaggedness
    # to track) and every 6th point for rail / subway / tram / ferry
    # (long straight runs, dense sampling wastes payload bytes).
    #
    # The MapLibre LineString geometry is hand-rolled via `parse_json` because
    # `make_list(pack_array(lon, lat))` flattens to a 1-D array in Kusto -
    # see the project memory note. The string round-trip costs ~2x on the
    # geometry-builder step but is the only correct construction today.
    r'''
.create-or-alter function with (folder = "Map", skipvalidation = "true") gtfs_shape_lines() {
    let route_by_shape =
        ['GeneralTransitFeed.TripsLatest']
        | where isnotempty(shapeId) and isnotempty(routeId)
        | summarize routeId = take_any(routeId), trips = dcount(tripId) by shapeId;
    ['GeneralTransitFeed.ShapesLatest']
    | where isnotnull(shapePtLat) and isnotnull(shapePtLon)
    | extend seq = toint(shapePtSequence)
    | where seq % 2 == 0
    | lookup route_by_shape on shapeId
    | lookup gtfs_routes() on routeId
    | where (routeType == "BUS") or (seq % 6 == 0)
    | extend coord = strcat("[", tostring(round(shapePtLon, 6)), ",",
                                 tostring(round(shapePtLat, 6)), "]")
    | sort by shapeId asc, seq asc
    | serialize
    | summarize coordinate_parts = make_list(coord, 3000),
                routeShortName = take_any(routeShortName),
                routeLongName = take_any(routeLongName),
                routeType = take_any(routeType),
                stroke_color = take_any(stroke_color),
                trips = take_any(trips),
                point_count = count() by shapeId, routeId
    | where array_length(coordinate_parts) > 1
    | extend geometry = parse_json(strcat('{"type":"LineString","coordinates":[',
                                          strcat_array(coordinate_parts, ","), ']}'))
    | extend label = strcat(routeShortName, " ", routeType)
    | project geometry, shapeId, routeId, routeShortName, routeLongName, routeType,
              trips, point_count, stroke_color, label
}
''',
    # ------------------------------------------------------------------
    # Major transit hubs: stops with the highest physical platform count or
    # ``parent_station`` group, colour-coded by size. We collapse platforms to
    # their parent station via the standard GTFS ``parent_station`` link,
    # then keep the busiest 500 hubs.
    r'''
.create-or-alter function with (folder = "Map", skipvalidation = "true") gtfs_hubs(minStops:int) {
    gtfs_stops()
    | extend hub_id = iff(isempty(parentStation),
                          strcat(tostring(round(stopLat, 3)), ":", tostring(round(stopLon, 3))),
                          parentStation)
    | summarize stop_count = dcount(stopId, 1), lat = avg(stopLat), lon = avg(stopLon),
                stopName = take_any(stopName), stations = countif(locationType == "STATION"),
                platforms = countif(locationType == "STOP") by hub_id
    | where stop_count >= minStops and isnotnull(lat) and isnotnull(lon)
    | top 500 by stop_count desc
    | extend fill_color = case(stop_count >= 40, "#d7191c",
                               stop_count >= 20, "#fdae61",
                               stop_count >= 10, "#2c7bb6",
                               "#41ab5d")
    | extend label = strcat(stopName, " (", tostring(stop_count), ")")
    | extend geometry = bag_pack("type", "Point", "coordinates", pack_array(lon, lat))
    | project geometry, hub_id, stopName, stop_count, stations, platforms, fill_color, label
}
''',
    # ------------------------------------------------------------------
    # All stops: every logical station (platform-collapsed) shown as a small
    # bubble starting at z11. For continental feeds with 250k+ stations the
    # raw query exceeds Fabric's 100k-feature-per-layer cap, so we stratify
    # by 0.025 degree (~2.5 km) geographic cells and keep the two most-served
    # stations per cell. That preserves coverage of small towns AND fits the
    # cap.
    r'''
.create-or-alter function with (folder = "Map", skipvalidation = "true") gtfs_stops_for_map() {
    gtfs_stops()
    | extend group_key = iff(isempty(parentStation), stopId, parentStation)
    | summarize stopName = take_any(stopName),
                lat = round(avg(stopLat), 5),
                lon = round(avg(stopLon), 5),
                platforms = dcount(stopId, 1),
                locationType = take_any(locationType)
            by group_key
    | extend cell = strcat(tostring(bin(lat, 0.025)), ":", tostring(bin(lon, 0.025)))
    | partition hint.strategy=native by cell ( top 2 by platforms desc )
    | extend marker_color = case(
        locationType == "STATION", "#0F172A",
        locationType == "ENTRANCE_EXIT", "#1E293B",
        locationType == "STOP", "#1E40AF",
        "#475569")
    | extend geometry = bag_pack("type", "Point", "coordinates", pack_array(lon, lat))
    | project geometry, stopName, platforms, marker_color
}
''',
    # ------------------------------------------------------------------
    # Live vehicle points: the most recent VehiclePosition per vehicle_id in
    # the lookback window, joined to its trip's static route metadata for
    # display colouring. Bounded to ``lookback`` minutes so quiet hours don't
    # show stale vehicles. ``arg_max`` projects only the needed columns to
    # keep shuffle bytes small.
    r'''
.create-or-alter function with (folder = "Map", skipvalidation = "true") gtfs_vehicle_points(lookback:timespan) {
    let latest_trips =
        ['GeneralTransitFeed.TripsLatest']
        | project trip_id = tripId, trip_route_id = routeId, tripHeadsign;
    let latest_routes = gtfs_routes();
    ['GeneralTransitFeed.VehiclePositionsFlat']
    | where ___time > ago(lookback)
    | where isnotempty(vehicle_id)
    | where isnotnull(latitude) and isnotnull(longitude)
    | summarize arg_max(___time, vehicle_label, route_id, trip_id, latitude, longitude,
                       bearing, current_status, occupancy_status, timestamp, ___source) by vehicle_id
    | lookup latest_trips on trip_id
    | extend route_id = iff(isempty(route_id), trip_route_id, route_id)
    | lookup latest_routes on $left.route_id == $right.routeId
    | extend age_min = datetime_diff('minute', now(), ___time)
    | extend status = current_status
    | extend freshness = case(age_min <= 2, "live", age_min <= 5, "fresh",
                              age_min <= 15, "stale", "old")
    | extend route_label = case(isnotempty(routeShortName), routeShortName,
                                isnotempty(route_id), route_id,
                                isnotempty(vehicle_label), vehicle_label,
                                vehicle_id)
    | extend fill_color = case(isnotempty(stroke_color), stroke_color,
                               routeType == "BUS", "#2E7D32",
                               routeType == "SUBWAY", "#00A1DE",
                               routeType == "RAIL", "#6D6E71",
                               "#455A64")
    | extend text_color = case(isnotempty(routeTextColor) and strlen(routeTextColor) == 6,
                               strcat("#", routeTextColor),
                               fill_color in ("#F6BC26", "#FFCC00", "#FCCC0A"), "#111111",
                               "#FFFFFF")
    | extend marker_color = fill_color
    | extend label = strcat(route_label, " ", vehicle_label)
    | extend geometry = bag_pack("type", "Point", "coordinates", pack_array(longitude, latitude))
    | project geometry, vehicle_id, vehicle_label, route_id, routeShortName, routeType, trip_id,
              latitude, longitude, bearing,
              status, occupancy_status, age_min, freshness, marker_color, fill_color, text_color,
              route_label, label, timestamp, ___source, ___time
}
''',
    # ------------------------------------------------------------------
    # Live vehicles rendered as bearing-oriented rectangles at z16+. Width
    # and length scale with latitude so the rectangles look right at street
    # zoom. Reuses ``gtfs_vehicle_points`` so the colouring stays consistent.
    r'''
.create-or-alter function with (folder = "Map", skipvalidation = "true") gtfs_vehicle_rectangles(lookback:timespan) {
    gtfs_vehicle_points(lookback)
    | extend heading = coalesce(bearing, 0.0)
    | extend rad = heading * pi() / 180.0
    | extend lon_scale = 1.0 / cos(latitude * pi() / 180.0)
    | extend half_len = 0.000055, half_wid = 0.000014
    | extend dlon_len = sin(rad) * half_len * lon_scale,
             dlat_len = cos(rad) * half_len,
             dlon_wid = cos(rad) * half_wid * lon_scale,
             dlat_wid = -sin(rad) * half_wid
    | extend p1 = strcat("[", tostring(round(longitude + dlon_len + dlon_wid, 7)), ",",
                              tostring(round(latitude + dlat_len + dlat_wid, 7)), "]"),
             p2 = strcat("[", tostring(round(longitude + dlon_len - dlon_wid, 7)), ",",
                              tostring(round(latitude + dlat_len - dlat_wid, 7)), "]"),
             p3 = strcat("[", tostring(round(longitude - dlon_len - dlon_wid, 7)), ",",
                              tostring(round(latitude - dlat_len - dlat_wid, 7)), "]"),
             p4 = strcat("[", tostring(round(longitude - dlon_len + dlon_wid, 7)), ",",
                              tostring(round(latitude - dlat_len + dlat_wid, 7)), "]")
    | extend geometry = parse_json(strcat('{"type":"Polygon","coordinates":[[',
                                          p1, ",", p2, ",", p3, ",", p4, ",", p1, ']]}'))
    | project geometry, vehicle_id, vehicle_label, route_id, routeShortName, routeType,
              status, occupancy_status, age_min, freshness,
              fill_color, stroke_color = "#111111", text_color, route_label,
              heading = round(heading, 0), bearing, timestamp, ___source, ___time
}
''',
    # ------------------------------------------------------------------
    # Geographic grid summaries: delay heatmap. Each cell aggregates the
    # average and worst-case delay in seconds across all stop arrivals in
    # the lookback window. Cells are coloured on a five-step ramp that
    # treats negative ("early") delays as cool and large positives as warm.
    r'''
.create-or-alter function with (folder = "Map", skipvalidation = "true") gtfs_delay_grid(lookback:timespan, resolution:real) {
    let stops = gtfs_stops() | project stop_id = stopId, stopLat, stopLon;
    ['GeneralTransitFeed.TripUpdateFlattened']
    | where ___time > ago(lookback)
    | where isnotempty(stop_id)
    | extend delay_s = coalesce(arrival_delay, departure_delay, delay)
    | where isnotnull(delay_s)
    | lookup stops on stop_id
    | extend lon0 = bin(stopLon, resolution), lat0 = bin(stopLat, resolution)
    | summarize updates = count(), stops = dcount(stop_id, 1),
                avg_delay_s = avg(delay_s), max_delay_s = max(delay_s) by lon0, lat0
    | extend avg_delay_min = round(avg_delay_s / 60.0, 1),
             max_delay_min = round(max_delay_s / 60.0, 1)
    | extend fill_color = case(avg_delay_s >= 900, "#7a0177",
                               avg_delay_s >= 300, "#d7191c",
                               avg_delay_s >= 120, "#fdae61",
                               avg_delay_s >= 0,   "#1a9850",
                               "#2c7bb6")
    | extend label = strcat(tostring(avg_delay_min), " min avg")
    | extend geometry = bag_pack("type", "Polygon", "coordinates", pack_array(pack_array(
        pack_array(lon0, lat0), pack_array(lon0 + resolution, lat0),
        pack_array(lon0 + resolution, lat0 + resolution), pack_array(lon0, lat0 + resolution),
        pack_array(lon0, lat0))))
    | project geometry, updates, stops, avg_delay_min, max_delay_min, fill_color, label
}
''',
    # ------------------------------------------------------------------
    # Vehicle data freshness grid: shows where RT vehicle pings are recent
    # vs. where they've gone stale. Useful for operations: if half the city
    # is grey, the feed is broken.
    r'''
.create-or-alter function with (folder = "Map", skipvalidation = "true") gtfs_vehicle_freshness_grid(lookback:timespan, resolution:real) {
    gtfs_vehicle_points(lookback)
    | extend lon0 = bin(longitude, resolution),
             lat0 = bin(latitude, resolution)
    | summarize vehicles = count(), avg_age = avg(age_min), max_age = max(age_min) by lon0, lat0
    | extend freshness = case(avg_age <= 2, "live",
                              avg_age <= 5, "fresh",
                              avg_age <= 15, "stale",
                              "old")
    | extend fill_color = case(freshness == "live",  "#00e676",
                               freshness == "fresh", "#7cb342",
                               freshness == "stale", "#fdae61",
                               "#8c8c8c")
    | extend label = strcat(tostring(vehicles), " vehicles, ", freshness)
    | extend geometry = bag_pack("type", "Polygon", "coordinates", pack_array(pack_array(
        pack_array(lon0, lat0), pack_array(lon0 + resolution, lat0),
        pack_array(lon0 + resolution, lat0 + resolution), pack_array(lon0, lat0 + resolution),
        pack_array(lon0, lat0))))
    | project geometry, vehicles, avg_age, max_age, freshness, fill_color, label
}
''',
    # ------------------------------------------------------------------
    # Active service alerts attached to a specific stop. Some feeds attach
    # alerts to routes only, in which case this layer is empty - the next
    # one (route_alert_lines) covers that case.
    r'''
.create-or-alter function with (folder = "Map", skipvalidation = "true") gtfs_alert_stops(lookback:timespan) {
    let stops = gtfs_stops() | project stop_id = stopId, stopName, stopLat, stopLon;
    ['GeneralTransitFeed.Alert']
    | where ___time > ago(lookback)
    | where informed_entity has "stop_id"
    | mv-apply ent = informed_entity on (
        project stop_id = tostring(ent.stop_id)
        | where isnotempty(stop_id)
    )
    | summarize alert_count = count() by stop_id
    | lookup stops on stop_id
    | extend marker_color = case(alert_count >= 5, "#d7191c",
                                 alert_count >= 2, "#fdae61",
                                 "#ffcc00")
    | extend label = strcat(tostring(alert_count), " alert(s)")
    | extend geometry = bag_pack("type", "Point", "coordinates", pack_array(stopLon, stopLat))
    | project geometry, stop_id, stopName, alert_count, marker_color, label
}
''',
    # ------------------------------------------------------------------
    # Active service alerts attached to a route. Severity is bucketed by
    # alert volume (a route with 50+ alerts in the lookback window is in
    # active crisis; 5 is moderate news). Used by the route_alert_lines
    # layer to highlight whole shapes in red/orange.
    r'''
.create-or-alter function with (folder = "Map", skipvalidation = "true") gtfs_route_alerts(lookback:timespan) {
    let latest_routes = gtfs_routes();
    ['GeneralTransitFeed.Alert']
    | where ___time > ago(lookback)
    | where informed_entity has "route_id"
    | extend sample_header = tostring(header_text.translation[0].text)
    | mv-apply ent = informed_entity on (
        project route_id = tostring(ent.route_id)
        | where isnotempty(route_id)
    )
    | summarize alert_count = count(),
                sample_header = take_any(sample_header) by route_id
    | lookup latest_routes on $left.route_id == $right.routeId
    | extend severity = case(alert_count >= 50, "critical",
                             alert_count >= 20, "major",
                             alert_count >= 5,  "moderate",
                             "minor")
    | extend alert_color = case(severity == "critical", "#B91C1C",
                                severity == "major",    "#F97316",
                                severity == "moderate", "#F59E0B",
                                "#FACC15")
    | project route_id, routeShortName, routeType, alert_count, severity,
              alert_color, sample_header, base_color = stroke_color
}
''',
    # ------------------------------------------------------------------
    # Coloured polyline overlay for routes with active alerts. The line is
    # drawn on top of the regular shape lines so the alert-affected routes
    # pop visually. Uses the same point-downsampling as gtfs_shape_lines.
    r'''
.create-or-alter function with (folder = "Map", skipvalidation = "true") gtfs_route_alert_lines(lookback:timespan) {
    let alerts = gtfs_route_alerts(lookback);
    let route_by_shape =
        ['GeneralTransitFeed.TripsLatest']
        | where isnotempty(shapeId) and isnotempty(routeId)
        | summarize routeId = take_any(routeId), trips = dcount(tripId) by shapeId;
    ['GeneralTransitFeed.ShapesLatest']
    | where isnotnull(shapePtLat) and isnotnull(shapePtLon)
    | extend seq = toint(shapePtSequence)
    | where seq % 6 == 0
    | lookup route_by_shape on shapeId
    | join kind=inner hint.strategy=broadcast alerts on $left.routeId == $right.route_id
    | extend coord = strcat("[", tostring(round(shapePtLon, 6)), ",",
                                 tostring(round(shapePtLat, 6)), "]")
    | sort by shapeId asc, seq asc
    | serialize
    | summarize coordinate_parts = make_list(coord, 3000),
                routeShortName = take_any(routeShortName),
                routeType = take_any(routeType),
                severity = take_any(severity),
                alert_color = take_any(alert_color),
                alert_count = take_any(alert_count),
                sample_header = take_any(sample_header) by shapeId, routeId
    | where array_length(coordinate_parts) > 1
    | extend geometry = parse_json(strcat('{"type":"LineString","coordinates":[',
                                          strcat_array(coordinate_parts, ","), ']}'))
    | extend label = strcat(routeShortName, " - ", tostring(alert_count), " alerts")
    | extend stroke_color = alert_color
    | project geometry, shapeId, routeId, routeShortName, routeType, severity, alert_count,
              sample_header, stroke_color, alert_color, label
}
''',
    # ------------------------------------------------------------------
    # Per-vehicle crowding (occupancy) layer. We drop ``EMPTY`` because
    # that's dominated by storage / layover vehicles in most feeds and the
    # blue colour visually drowns out the operationally interesting buckets.
    r'''
.create-or-alter function with (folder = "Map", skipvalidation = "true") gtfs_crowding(lookback:timespan) {
    gtfs_vehicle_points(lookback)
    | extend crowding = case(
        occupancy_status == "MANY_SEATS_AVAILABLE",     "spacious",
        occupancy_status == "FEW_SEATS_AVAILABLE",      "moderate",
        occupancy_status == "STANDING_ROOM_ONLY",       "crowded",
        occupancy_status == "CRUSHED_STANDING_ROOM_ONLY","very crowded",
        occupancy_status == "FULL",                     "full",
        occupancy_status == "NOT_ACCEPTING_PASSENGERS", "not boarding",
        "")
    | where isnotempty(crowding)
    | extend crowding_color = case(
        crowding == "spacious",     "#10B981",
        crowding == "moderate",     "#F59E0B",
        crowding == "crowded",      "#EF4444",
        crowding == "very crowded", "#B91C1C",
        crowding == "full",         "#7F1D1D",
        crowding == "not boarding", "#6B7280",
        "#9CA3AF")
    | extend label = strcat(route_label, " - ", crowding)
    | project geometry, vehicle_id, vehicle_label, route_id, routeShortName, routeType,
              status, occupancy_status, crowding, crowding_color, age_min, freshness,
              timestamp, ___source, ___time, label
}
''',
    # ------------------------------------------------------------------
    # Three-line arrival board per stop: the next ~3 arrivals in the
    # ``horizon`` window. The partition-by-top-N pattern avoids a global sort
    # over the entire TripUpdate slice - it parallelises per stop and keeps
    # only the earliest 3 per stop. The label_tiny / compact / detail
    # extensions are zoom-band variants - the wire script binds each to a
    # different minZoom/maxZoom range so labels grow as the user zooms in.
    r'''
.create-or-alter function with (folder = "Map", skipvalidation = "true") gtfs_stop_arrival_boards(lookback:timespan, horizon:timespan) {
    let stops = gtfs_stops()
        | project stop_id = stopId, stopName, stopLat, stopLon;
    let route_lookup = gtfs_routes()
        | project routeId, routeShortName, routeType, stroke_color;
    let trip_lookup = ['GeneralTransitFeed.TripsLatest']
        | project trip_id = tripId, static_route_id = routeId,
                  static_direction_id = directionId, tripHeadsign;
    ['GeneralTransitFeed.TripUpdateFlattened']
    | where ___time > ago(lookback)
    | where isnotempty(stop_id)
    | extend due_time = coalesce(arrival_time, departure_time)
    | where isnotnull(due_time) and due_time between (now() .. now() + horizon)
    | summarize arg_min(due_time, route_id, direction_id) by stop_id, trip_id
    | lookup stops on stop_id
    | lookup trip_lookup on trip_id
    | extend route_id = iff(isempty(route_id), static_route_id, route_id)
    | extend dir_id = case(direction_id == 0, "0", direction_id == 1, "1",
                           static_direction_id == "0", "0", static_direction_id == "1", "1",
                           "?")
    | lookup route_lookup on $left.route_id == $right.routeId
    | extend route = case(isnotempty(routeShortName), routeShortName,
                          isnotempty(route_id), route_id, "?")
    | extend dir_arrow = case(dir_id == "0", "^", dir_id == "1", "v", ".")
    | extend mins = toint(datetime_diff('minute', due_time, now()))
    | extend row_text = strcat(route, dir_arrow, " ", tostring(mins), "m")
    | partition hint.strategy=native by stop_id (
        top 3 by due_time asc
        | extend rn = row_number()
    )
    | summarize arrival_1 = take_anyif(row_text, rn == 1),
                arrival_2 = take_anyif(row_text, rn == 2),
                arrival_3 = take_anyif(row_text, rn == 3),
                next_min = min(mins),
                arrival_count = count(),
                stopName = take_any(stopName),
                stopLat = take_any(stopLat),
                stopLon = take_any(stopLon) by stop_id
    | extend label_tiny = arrival_1
    | extend label_compact = strcat(arrival_1,
                                    iff(isnotempty(arrival_2), strcat("  ", arrival_2), ""))
    | extend label_detail = strcat(stopName, "\n", arrival_1,
                                   iff(isnotempty(arrival_2), strcat("  ", arrival_2), ""),
                                   iff(isnotempty(arrival_3), strcat("  ", arrival_3), ""))
    | extend label = label_compact
    | extend fill_color = "#111111", stroke_color = "#FFFFFF"
    | extend geometry = bag_pack("type", "Point", "coordinates", pack_array(stopLon, stopLat))
    | project geometry, stop_id, stopName, arrival_1, arrival_2, arrival_3,
              label_tiny, label_compact, label_detail, next_min, arrival_count,
              fill_color, stroke_color, label
}
''',
    # ------------------------------------------------------------------
    # Multi-modal stations: stops served by 2+ distinct route_types in the
    # recent activity window. These are the natural interchange points -
    # bus + tram, bus + rail, etc. Reverses the data flow vs. the obvious
    # approach (active stops first, then resolve routes) to avoid scanning
    # the entire Trips table.
    r'''
.create-or-alter function with (folder = "Map", skipvalidation = "true") gtfs_multimodal_stations() {
    let stops = gtfs_stops();
    let routes = gtfs_routes() | project routeId, routeType;
    let active = ['GeneralTransitFeed.TripUpdateFlattened']
        | where ___time > ago(2h)
        | where isnotempty(stop_id) and isnotempty(trip_id)
        | distinct trip_id, stop_id;
    let active_trip_ids = active | distinct trip_id;
    let trip_routes = ['GeneralTransitFeed.TripsLatest']
        | where tripId in (active_trip_ids)
        | project trip_id = tripId, routeId
        | lookup routes on routeId;
    active
    | join kind=inner hint.shufflekey=trip_id trip_routes on trip_id
    | summarize modes = make_set(routeType, 10) by stop_id
    | extend mode_count = array_length(modes)
    | where mode_count >= 2
    | lookup (stops | project stop_id = stopId, stopName, stopLat, stopLon, parentStation) on stop_id
    | extend hub_key = iff(isempty(parentStation), stop_id, parentStation)
    | summarize modes = take_any(modes), mode_count = max(mode_count),
                lat = avg(stopLat), lon = avg(stopLon), stopName = take_any(stopName) by hub_key
    | top 1500 by mode_count desc
    | extend marker_color = case(mode_count >= 4, "#7C3AED",
                                 mode_count >= 3, "#0891B2",
                                 "#0EA5E9")
    | extend label = strcat(stopName, " (", tostring(mode_count), "x)")
    | extend geometry = bag_pack("type", "Point", "coordinates", pack_array(lon, lat))
    | project geometry, hub_key, stopName, mode_count, modes, marker_color, label
}
''',
]


# ---------------------------------------------------------------------------
# Layer styling - shared between layers. Fabric Maps doesn't honour
# ``["get", "field"]`` data-driven colours in bubble/line/polygon paint
# properties, so we use a hybrid: ``seriesGroup`` + ``customColors`` (for the
# Data Layers panel legend) AND a MapLibre ``match`` expression on the paint
# property (which is what actually renders). Both are written at deploy
# time; ``customColors`` is populated from a per-layer ``distinct`` query.
# ---------------------------------------------------------------------------

LABEL_BASE = {
    "enabled": False,
    "size": 11,
    "color": "#111111",
    "textStrokeColor": "#FFFFFF",
    "textStrokeWidth": 2,
    "allowOverlap": False,
}

STOP_PALETTE_SEED = {
    "#0F172A": "#0F172A",
    "#1E293B": "#1E293B",
    "#1E40AF": "#1E40AF",
    "#475569": "#475569",
}

CROWDING_PALETTE_SEED = {
    "#10B981": "#10B981", "#F59E0B": "#F59E0B", "#EF4444": "#EF4444",
    "#B91C1C": "#B91C1C", "#7F1D1D": "#7F1D1D", "#6B7280": "#6B7280",
    "#9CA3AF": "#9CA3AF",
}

ALERT_STOP_PALETTE_SEED = {"#ffcc00": "#ffcc00", "#fdae61": "#fdae61", "#d7191c": "#d7191c"}
ALERT_SEVERITY_PALETTE_SEED = {
    "#B91C1C": "#B91C1C", "#F97316": "#F97316", "#F59E0B": "#F59E0B", "#FACC15": "#FACC15",
}
HUB_PALETTE_SEED = {
    "#d7191c": "#d7191c", "#fdae61": "#fdae61",
    "#2c7bb6": "#2c7bb6", "#41ab5d": "#41ab5d",
}
DELAY_PALETTE_SEED = {
    "#7a0177": "#7a0177", "#d7191c": "#d7191c", "#fdae61": "#fdae61",
    "#1a9850": "#1a9850", "#2c7bb6": "#2c7bb6",
}
FRESHNESS_PALETTE_SEED = {
    "#00e676": "#00e676", "#7cb342": "#7cb342",
    "#fdae61": "#fdae61", "#8c8c8c": "#8c8c8c",
}
MULTIMODAL_PALETTE_SEED = {"#7C3AED": "#7C3AED", "#0891B2": "#0891B2", "#0EA5E9": "#0EA5E9"}


def _series(column: str, palette: dict[str, str]) -> dict[str, Any]:
    return {
        "enableSeriesGroup": True,
        "seriesGroup": column,
        "customColors": dict(palette),
    }


def _color_match(column: str, palette: dict[str, str], fallback: str = "#888888") -> list[Any]:
    expr: list[Any] = ["match", ["get", column]]
    for value, color in palette.items():
        expr.append(value)
        expr.append(color)
    expr.append(fallback)
    return expr


def line_options(*, visible: bool, width: int = 3, opacity: float = 0.86,
                 min_zoom: float | None = None, color_column: str = "stroke_color",
                 palette: dict[str, str] | None = None) -> dict[str, Any]:
    pal = palette if palette is not None else {}
    opts: dict[str, Any] = {
        "type": "vector",
        "visible": visible,
        "lineOptions": {
            "strokeColor": "#888888",
            "strokeWidth": width,
            "strokeOpacity": opacity,
            **_series(color_column, pal),
        },
        "dataLabelKeys": ["label"],
        "dataLabelOptions": dict(LABEL_BASE),
        "tooltipKeys": ["label", "routeShortName", "routeType", "routeId", "shapeId", "trips",
                        "severity", "alert_count", "sample_header"],
        "enablePopups": True,
    }
    if min_zoom is not None:
        opts["minZoom"] = min_zoom
    return opts


def bubble_options(*, visible: bool, radius: int = 4,
                   labels: bool = False, label_size: int = 11,
                   min_zoom: float | None = None, max_zoom: float | None = None,
                   color_column: str = "fill_color",
                   palette: dict[str, str] | None = None,
                   tooltip_keys: list[str] | None = None,
                   stroke_color: str = "#FFFFFF") -> dict[str, Any]:
    pal = palette if palette is not None else {}
    opts: dict[str, Any] = {
        "type": "vector",
        "visible": visible,
        "pointLayerType": "bubble",
        "bubbleOptions": {
            "color": "#888888",
            "radius": radius,
            "strokeColor": stroke_color,
            "strokeWidth": 1,
            "opacity": 0.92,
            **_series(color_column, pal),
        },
        "dataLabelKeys": ["label"],
        "dataLabelOptions": dict(LABEL_BASE, enabled=labels, size=label_size),
        "tooltipKeys": tooltip_keys or ["label"],
        "enablePopups": True,
    }
    if min_zoom is not None:
        opts["minZoom"] = min_zoom
    if max_zoom is not None:
        opts["maxZoom"] = max_zoom
    return opts


def polygon_options(*, visible: bool, color_column: str = "fill_color",
                    palette: dict[str, str] | None = None,
                    fill_opacity: float = 0.62,
                    stroke_color: Any = "#202020",
                    stroke_width: int = 0,
                    labels: bool = False, label_size: int = 10) -> dict[str, Any]:
    pal = palette if palette is not None else {}
    return {
        "type": "vector",
        "visible": visible,
        "polygonOptions": {
            "fillColor": "#888888",
            "fillOpacity": fill_opacity,
            **_series(color_column, pal),
        },
        "lineOptions": {
            "strokeColor": stroke_color,
            "strokeWidth": stroke_width,
            "strokeOpacity": 0.15,
        },
        "dataLabelKeys": ["label"],
        "dataLabelOptions": dict(LABEL_BASE, enabled=labels, size=label_size),
        "tooltipKeys": ["label", "stop_count", "updates", "stops", "avg_delay_min",
                        "max_delay_min", "vehicles", "avg_age", "max_age", "freshness"],
        "enablePopups": True,
    }


def arrival_board_options(*, min_zoom: float, max_zoom: float | None,
                          label_size: int, allow_overlap: bool) -> dict[str, Any]:
    opts: dict[str, Any] = {
        "type": "vector",
        "visible": True,
        "minZoom": min_zoom,
        "pointLayerType": "bubble",
        "bubbleOptions": {
            "color": "#111111",
            "radius": 2,
            "strokeColor": "#FFFFFF",
            "strokeWidth": 1,
            "opacity": 0.85,
        },
        "dataLabelKeys": ["label"],
        "dataLabelOptions": dict(
            LABEL_BASE,
            enabled=True,
            size=label_size,
            color="#0A0A0A",
            textStrokeColor="#FFFFFF",
            textStrokeWidth=3,
            allowOverlap=allow_overlap,
        ),
        "tooltipKeys": ["stopName", "arrival_1", "arrival_2", "arrival_3", "next_min", "arrival_count"],
        "enablePopups": True,
    }
    if max_zoom is not None:
        opts["maxZoom"] = max_zoom
    return opts


def vehicle_rectangle_options() -> dict[str, Any]:
    return {
        "type": "vector",
        "visible": True,
        "minZoom": 16,
        "polygonOptions": {
            "fillColor": "#888888",
            "fillOpacity": 0.95,
            **_series("fill_color", {}),
        },
        "lineOptions": {
            "strokeColor": "#202020",
            "strokeWidth": 1,
            "strokeOpacity": 0.95,
        },
        "dataLabelKeys": ["route_label"],
        "dataLabelOptions": dict(
            LABEL_BASE,
            enabled=True,
            size=9,
            color="#FFFFFF",
            textStrokeColor="#000000",
            textStrokeWidth=1.5,
            allowOverlap=True,
        ),
        "tooltipKeys": [
            "route_label", "vehicle_label", "vehicle_id", "route_id",
            "routeType", "status", "occupancy_status", "heading",
            "freshness", "age_min", "timestamp", "___source",
        ],
        "enablePopups": True,
    }


def _text_filter(field: str) -> dict[str, Any]:
    return {
        "id": str(uuid.uuid4()),
        "type": "text",
        "field": field,
        "locked": False,
        "value": [],
    }


# ---------------------------------------------------------------------------
# Layer declarations - one entry per Fabric Map vector layer.
# ---------------------------------------------------------------------------

@dataclass
class Layer:
    name: str
    kql: str
    options: dict[str, Any]
    filters: list[dict[str, Any]]


def _layers() -> list[Layer]:
    return [
        Layer(
            "GTFS - Rail, subway, tram & ferry",
            'gtfs_shape_lines() | where routeType in ("SUBWAY", "RAIL", "TRAM", "FERRY", "CABLE_CAR", "GONDOLA")',
            line_options(visible=True, width=4, opacity=0.92, min_zoom=8.5),
            [_text_filter("routeType"), _text_filter("routeShortName")],
        ),
        Layer(
            "GTFS - Bus routes",
            'gtfs_shape_lines() | where routeType == "BUS"',
            line_options(visible=True, width=2, opacity=0.85, min_zoom=11.5),
            [_text_filter("routeShortName")],
        ),
        Layer(
            "GTFS - Live vehicles",
            "gtfs_vehicle_points(30m)",
            bubble_options(
                visible=True, radius=4, min_zoom=12, max_zoom=16,
                color_column="fill_color",
                tooltip_keys=[
                    "route_label", "vehicle_label", "route_id",
                    "routeType", "status", "freshness", "age_min", "timestamp",
                ],
            ),
            [_text_filter("status"), _text_filter("routeType")],
        ),
        Layer(
            "GTFS - Live vehicles (detail)",
            "gtfs_vehicle_rectangles(30m)",
            vehicle_rectangle_options(),
            [_text_filter("status"), _text_filter("routeType")],
        ),
        Layer(
            "GTFS - Major transit hubs",
            "gtfs_hubs(5)",
            bubble_options(
                visible=True, radius=6, labels=True, label_size=11, min_zoom=11,
                color_column="fill_color", palette=HUB_PALETTE_SEED,
                tooltip_keys=["label", "stopName", "stop_count", "stations", "platforms"],
            ),
            [],
        ),
        Layer(
            "GTFS - All stops",
            "gtfs_stops_for_map()",
            bubble_options(
                visible=True, radius=5, labels=True, label_size=10, min_zoom=11,
                color_column="marker_color", palette=STOP_PALETTE_SEED,
                tooltip_keys=["stopName", "platforms"],
            ),
            [],
        ),
        Layer(
            "GTFS - Service alerts",
            "gtfs_alert_stops(24h)",
            bubble_options(
                visible=False, radius=7, labels=True, label_size=11, min_zoom=10,
                color_column="marker_color", palette=ALERT_STOP_PALETTE_SEED,
                tooltip_keys=["label", "stopName", "alert_count"],
            ),
            [],
        ),
        Layer(
            "GTFS - Routes with active alerts",
            "gtfs_route_alert_lines(2h)",
            line_options(
                visible=True, width=6, opacity=0.7, min_zoom=10,
                color_column="alert_color", palette=ALERT_SEVERITY_PALETTE_SEED,
            ),
            [_text_filter("severity"), _text_filter("routeType")],
        ),
        Layer(
            "GTFS - Vehicle crowding",
            "gtfs_crowding(30m)",
            bubble_options(
                visible=False, radius=5, min_zoom=13,
                color_column="crowding_color", palette=CROWDING_PALETTE_SEED,
                tooltip_keys=["label", "route_label", "routeShortName", "crowding",
                              "occupancy_status", "status", "vehicle_label", "age_min"],
            ),
            [_text_filter("crowding"), _text_filter("routeType")],
        ),
        Layer(
            "GTFS - Multi-modal stations",
            "gtfs_multimodal_stations()",
            bubble_options(
                visible=True, radius=6, labels=True, label_size=10, min_zoom=8,
                color_column="marker_color", palette=MULTIMODAL_PALETTE_SEED,
                tooltip_keys=["label", "stopName", "mode_count", "modes"],
            ),
            [],
        ),
        Layer(
            "GTFS - Vehicle data freshness",
            "gtfs_vehicle_freshness_grid(30m, 0.01)",
            polygon_options(
                visible=False, color_column="fill_color", palette=FRESHNESS_PALETTE_SEED,
            ),
            [_text_filter("freshness")],
        ),
        Layer(
            "GTFS - Delay heatmap",
            "gtfs_delay_grid(30m, 0.01)",
            polygon_options(
                visible=False, color_column="fill_color", palette=DELAY_PALETTE_SEED,
            ),
            [],
        ),
        Layer(
            "GTFS - Arrival boards",
            "gtfs_stop_arrival_boards(20m, 60m) | extend label = label_tiny | top 6000 by next_min asc",
            arrival_board_options(min_zoom=15.0, max_zoom=17.5, label_size=11, allow_overlap=False),
            [],
        ),
        Layer(
            "GTFS - Arrival boards (street)",
            "gtfs_stop_arrival_boards(20m, 60m) | extend label = label_compact | top 6000 by next_min asc",
            arrival_board_options(min_zoom=17.5, max_zoom=18.7, label_size=12, allow_overlap=False),
            [],
        ),
        Layer(
            "GTFS - Arrival boards (detail)",
            "gtfs_stop_arrival_boards(20m, 60m) | extend label = label_detail | top 6000 by next_min asc",
            arrival_board_options(min_zoom=18.7, max_zoom=None, label_size=13, allow_overlap=True),
            [],
        ),
    ]


# ---------------------------------------------------------------------------
# Map definition patching.
# ---------------------------------------------------------------------------

def _b64(s: str) -> str:
    return base64.b64encode(s.encode("utf-8")).decode("ascii")


def _get_definition(fab: requests.Session, api_base: str, workspace_id: str,
                    map_id: str) -> tuple[dict[str, Any], dict[str, dict[str, Any]]]:
    res = _poll_lro(
        fab,
        fab.post(f"{api_base}/workspaces/{workspace_id}/items/{map_id}/getDefinition"),
    )
    parts = {p["path"]: p for p in res["definition"]["parts"]}
    if "map.json" not in parts:
        raise RuntimeError("Map definition has no map.json part")
    mp = json.loads(base64.b64decode(parts["map.json"]["payload"]).decode("utf-8"))
    mp.setdefault("dataSources", [])
    mp.setdefault("iconSources", [])
    mp.setdefault("layerSources", [])
    mp.setdefault("layerSettings", [])
    if "$schema" not in mp:
        mp["$schema"] = ("https://developer.microsoft.com/json-schemas/fabric/item/map/"
                         "definition/2.0.0/schema.json")
    return mp, parts


def _put_definition(fab: requests.Session, api_base: str, workspace_id: str,
                    map_id: str, mp: dict[str, Any],
                    parts: dict[str, dict[str, Any]]) -> None:
    parts["map.json"] = {
        "path": "map.json",
        "payload": _b64(json.dumps(mp, indent=2)),
        "payloadType": "InlineBase64",
    }
    r = fab.post(
        f"{api_base}/workspaces/{workspace_id}/items/{map_id}/updateDefinition",
        json={"definition": {"parts": list(parts.values())}},
    )
    print(f"updateDefinition HTTP {r.status_code}")
    _poll_lro(fab, r)


def _bbox(ks: requests.Session, kusto_uri: str, kusto_db: str) -> Optional[tuple[float, float, float, float, int]]:
    """Return (lat_p01, lat_p99, lon_p01, lon_p99, n) or None on failure."""
    try:
        frame = _kql_query(ks, kusto_uri, kusto_db, "gtfs_bbox()")
    except Exception as exc:
        print(f"  bbox lookup failed: {exc}")
        return None
    if not frame or not frame.get("Rows"):
        return None
    cols = [c["ColumnName"] for c in frame["Columns"]]
    row = frame["Rows"][0]
    rec = dict(zip(cols, row))
    if rec.get("cnt", 0) == 0:
        return None
    return (
        float(rec["lat_p01"]),
        float(rec["lat_p99"]),
        float(rec["lon_p01"]),
        float(rec["lon_p99"]),
        int(rec["cnt"]),
    )


def _zoom_for_extent(lat_span: float, lon_span: float) -> float:
    """Pick a sensible default zoom for the bounding box. Numbers are tuned for
    a 1600x1000 viewport - they err on the side of zooming OUT slightly so the
    full source is visible at first render."""
    span = max(lat_span, lon_span / 2.0)  # account for Mercator distortion
    if span >= 30:  return 3.5   # continental (USA, Europe-wide)
    if span >= 15:  return 4.5   # multi-country
    if span >= 8:   return 5.5   # large country (Germany, France)
    if span >= 4:   return 6.7
    if span >= 2:   return 8.0
    if span >= 1:   return 9.5
    if span >= 0.5: return 10.6
    if span >= 0.2: return 11.5
    return 12.5


def _set_basemap(mp: dict[str, Any], bbox: Optional[tuple[float, float, float, float, int]]) -> None:
    if bbox is None:
        center = [0.0, 30.0]
        zoom = 3.0
    else:
        lat_p01, lat_p99, lon_p01, lon_p99, _ = bbox
        center = [(lon_p01 + lon_p99) / 2.0, (lat_p01 + lat_p99) / 2.0]
        zoom = _zoom_for_extent(lat_p99 - lat_p01, lon_p99 - lon_p01)
    mp["basemap"] = {
        "options": {
            "center": center,
            "zoom": zoom,
            "style": "grayscale_light",
            "showLabels": True,
        },
        "controls": {
            "zoom": True, "pitch": True, "compass": True, "scale": True,
            "traffic": False, "style": True,
        },
        "backgroundColor": "#FFFFFF",
        "theme": "light",
    }
    print(f"  basemap center={center} zoom={zoom}")


def _populate_palette(ks: requests.Session, kusto_uri: str, kusto_db: str,
                      layer: Layer) -> None:
    """For each seriesGroup-bound paint property on the layer, fetch the
    distinct values from the live data and populate ``customColors`` as an
    identity map. Also write a MapLibre ``match`` expression to the paint
    property (Fabric's ``seriesGroup`` populates the legend but does not
    actually drive paint color)."""
    paint_key_for = {
        "bubbleOptions": "color",
        "lineOptions": "strokeColor",
        "polygonOptions": "fillColor",
    }
    for sub, paint_key in paint_key_for.items():
        block = layer.options.get(sub)
        if not block or not block.get("enableSeriesGroup"):
            continue
        column = block.get("seriesGroup")
        if not column:
            continue
        try:
            frame = _kql_query(
                ks, kusto_uri, kusto_db,
                f"{layer.kql}\n| where isnotempty({column})"
                f"\n| distinct {column}\n| take 50",
            )
            values = [row[0] for row in (frame.get("Rows") or []) if row and row[0]]
        except Exception as exc:
            print(f"    palette enumeration failed for {layer.name}/{column}: {exc}")
            values = []
        if not values:
            continue
        block.setdefault("customColors", {})
        for v in values:
            block["customColors"].setdefault(v, v)
        block[paint_key] = _color_match(column, block["customColors"])
        print(f"    palette {column}: {len(block['customColors'])} colors")


# ---------------------------------------------------------------------------
# Top-level wiring entry point.
# ---------------------------------------------------------------------------

def wire(*, workspace_id: str, map_id: str, kql_db_id: str,
         kusto_uri: str, kusto_db: str,
         fabric_token: str, kusto_token: str,
         api_base: str = "https://api.fabric.microsoft.com/v1") -> None:
    fab = _session(fabric_token)
    ks = _session(kusto_token)

    # 1. Create/refresh the helper KQL functions in the target database.
    print(f"Creating {len(GTFS_FUNCTIONS)} helper functions in {kusto_db}")
    for f in GTFS_FUNCTIONS:
        head = next((line.strip() for line in f.splitlines() if line.strip()), "")
        print(f"  {head[:110]}")
        _kql_mgmt(ks, kusto_uri, kusto_db, f)

    # 2. Look up the source's geographic footprint to centre the basemap.
    print("Discovering bounding box from gtfs_bbox()")
    bbox = _bbox(ks, kusto_uri, kusto_db)
    if bbox is None:
        print("  no stops indexed yet; using world view")
    else:
        lat_p01, lat_p99, lon_p01, lon_p99, n = bbox
        print(f"  {n} stops; lat=[{lat_p01:.3f}, {lat_p99:.3f}]"
              f" lon=[{lon_p01:.3f}, {lon_p99:.3f}]")

    # 3. Patch the map definition idempotently.
    mp, parts = _get_definition(fab, api_base, workspace_id, map_id)
    _set_basemap(mp, bbox)

    # Drop previously-wired layers whose source is bound to this KQL DB so we
    # don't accumulate stale layers across re-runs.
    removed_src_ids = {
        s["id"] for s in mp.get("layerSources", [])
        if s.get("itemId") == kql_db_id
    }
    if removed_src_ids:
        print(f"  removing {len(removed_src_ids)} pre-existing GTFS layer source(s)")
    mp["layerSettings"] = [ls for ls in mp.get("layerSettings", [])
                           if ls.get("sourceId") not in removed_src_ids]
    mp["layerSources"] = [s for s in mp.get("layerSources", [])
                          if s["id"] not in removed_src_ids]
    for path in list(parts):
        if path.startswith("queries/layerSource-"):
            sid = path.split("layerSource-", 1)[1].split(".kql", 1)[0]
            if sid in removed_src_ids:
                del parts[path]

    # Ensure this KQL DB is registered as a data source.
    if not any(d.get("itemId") == kql_db_id for d in mp["dataSources"]):
        mp["dataSources"].append({
            "itemType": "KqlDatabase",
            "workspaceId": workspace_id,
            "itemId": kql_db_id,
        })

    # 4. Add each layer, validating the query and populating the palette.
    for layer in _layers():
        print(f"  layer {layer.name}")
        try:
            cnt_frame = _kql_query(ks, kusto_uri, kusto_db, f"{layer.kql}\n| count")
            cnt = cnt_frame["Rows"][0][0] if cnt_frame and cnt_frame.get("Rows") else "?"
            print(f"    rows: {cnt}")
        except Exception as exc:
            print(f"    validation failed (skipping): {exc}")
            continue

        _populate_palette(ks, kusto_uri, kusto_db, layer)

        src_id = str(uuid.uuid4())
        mp["layerSources"].append({
            "id": src_id,
            "name": f"{layer.name}_source",
            "type": "kusto",
            "options": {"cluster": False},
            "itemId": kql_db_id,
            "refreshIntervalMs": 0,
        })
        mp["layerSettings"].append({
            "id": str(uuid.uuid4()),
            "name": layer.name,
            "sourceId": src_id,
            "geometryColumnName": "geometry",
            "filters": layer.filters,
            "options": layer.options,
        })
        parts[f"queries/layerSource-{src_id}.kql"] = {
            "path": f"queries/layerSource-{src_id}.kql",
            "payload": _b64(layer.kql),
            "payloadType": "InlineBase64",
        }

    _put_definition(fab, api_base, workspace_id, map_id, mp, parts)
    print(f"OK - map {map_id} updated with {len(_layers())} layers")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("--workspace-id", default=os.environ.get("FABRIC_WORKSPACE_ID"))
    ap.add_argument("--map-id",       default=os.environ.get("FABRIC_MAP_ID"))
    ap.add_argument("--kql-db-id",    default=os.environ.get("FABRIC_KQL_DB_ID"))
    ap.add_argument("--kusto-uri",    default=os.environ.get("KUSTO_CLUSTER_URI"))
    ap.add_argument("--kusto-db",     default=os.environ.get("KUSTO_DB", "gtfs"))
    ap.add_argument("--api-base",     default=os.environ.get(
        "FABRIC_API_BASE", "https://api.fabric.microsoft.com/v1"))
    args = ap.parse_args(argv)

    missing = [n for n in ("workspace_id", "map_id", "kql_db_id", "kusto_uri")
               if not getattr(args, n)]
    if missing:
        ap.error("missing required: " + ", ".join("--" + m.replace("_", "-") for m in missing))
        return 2

    fabric_token = _get_token("FABRIC_TOKEN", "https://api.fabric.microsoft.com/.default")
    kusto_token = _get_token("KUSTO_TOKEN", "https://kusto.fabric.microsoft.com/.default")

    wire(
        workspace_id=args.workspace_id,
        map_id=args.map_id,
        kql_db_id=args.kql_db_id,
        kusto_uri=args.kusto_uri,
        kusto_db=args.kusto_db,
        fabric_token=fabric_token,
        kusto_token=kusto_token,
        api_base=args.api_base,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
