[mypy]
python_version = 3.11
files = feeders
explicit_package_bases = True
ignore_missing_imports = True
follow_imports = silent
warn_unused_ignores = False
show_error_codes = True
exclude = (?x)(^feeders/.*/tests/|^feeders/.*/.*_producer/)
disable_error_code = arg-type, var-annotated, union-attr, assignment, name-defined, return-value, index, misc, attr-defined, call-overload, list-item, no-redef, type-var, dict-item, annotation-unchecked, operator
