[mypy]
python_version = 3.11
files = feeders
explicit_package_bases = True
ignore_missing_imports = True
follow_imports = silent
warn_unused_ignores = False
show_error_codes = True
exclude = (?x)(^feeders/.*/tests/|^feeders/.*/.*_producer/|/build/)
disable_error_code = var-annotated, union-attr, assignment, return-value, index, misc, call-overload, list-item, no-redef, type-var, dict-item, annotation-unchecked, operator
