[tool.poetry]
name = "mode-s-producer-data"
version = "0.1.0"
description = "A package for handling Avro schema data"
authors = ["Your Name"]
license = "MIT"
packages = [ { include = "mode_s_producer_data", from="src" } ]

[tool.poetry.dependencies]
python = "<4.0,>=3.10"
orjson = "^3.10"

[tool.poetry.dev-dependencies]
pylint = "^3.2.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"