[build-system]
requires = ["poetry-core>=1.1.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "nextbus"
version = "0.1.0"
description = "A project to fetch data from NextBus API"
authors = ["Clemens Vasters <clemensv@microsoft.com>"]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.31.0"
azure-eventhub = "^5.11.3"
cloudevents = "^1.9.0"

[build-system.scripts]
nextbus-cli = "nextbus.nextbus:main"
