# Regenerate the MQTT producer (mqttclient style) from the authoritative
# xreg manifest. The companion Kafka producer is regenerated by
# generate_producer.ps1.

. (Join-Path $PSScriptRoot "..\tools\require-xrcg.ps1")
Assert-XrcgVersion

xrcg generate `
    --style mqttclient `
    --language py `
    --definitions xreg\bfs_odl.xreg.json `
    --endpoint de.bfs.odl.Mqtt `
    --projectname bfs_odl_mqtt_producer `
    --output bfs_odl_mqtt_producer
