# Regenerate the MQTT producer (mqttclient style) from the authoritative
# xreg manifest. The companion Kafka producer is regenerated by
# generate_producer.ps1.

. (Join-Path $PSScriptRoot "..\tools\require-xrcg.ps1")
Assert-XrcgVersion

xrcg generate `
    --style mqttclient `
    --language py `
    --definitions xreg\nve_hydro.xreg.json `
    --endpoint NO.NVE.Hydrology.Mqtt `
    --projectname nve_hydro_mqtt_producer `
    --output nve_hydro_mqtt_producer
