# Regenerate the MQTT producer (mqttclient style) from the authoritative
# xreg manifest. The companion Kafka producer is regenerated by
# generate_producer.ps1.

. (Join-Path $PSScriptRoot "..\tools\require-xrcg.ps1")
Assert-XrcgVersion

xrcg generate `
    --style mqttclient `
    --language py `
    --definitions xreg\chmi_hydro.xreg.json `
    --endpoint CZ.Gov.CHMI.Hydro.Mqtt `
    --projectname chmi_hydro_mqtt_producer `
    --output chmi_hydro_mqtt_producer
