[tool.poetry]
name = "rssbridge-producer-kafka-producer"
description = "rssbridge_producer_kafka_producer Apache Kafka consumer library"
authors = ["Clemens Vasters <clemensv@microsoft.com>"]
readme = "README.md"
version = "0.1.0"  # Placeholder version, dynamic versioning can be handled with plugins
packages = [{include = "rssbridge_producer_kafka_producer", from = "src"}]

[tool.poetry.dependencies]
python = "<4.0,>=3.10"
rssbridge-producer-kafka-producer = { path = "../../../rssbridge_producer/rssbridge_producer_kafka_producer", develop = true }
rssbridge-producer-data = { path = "../../../rssbridge_producer/rssbridge_producer_data", develop = true }
confluent-kafka = ">=2.5.3"
cloudevents = ">=1.11.0"

[tool.poetry.dev-dependencies]
pytest = ">=8.3.2"
flake8 = ">=7.1.1"
pylint = ">=3.2.7"
mypy = ">=1.11.2"
testcontainers = ">=4.8.1"
pytest-asyncio = ">=0.24.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"