[pytest]
pythonpath =
    noaa_swpc_l1_core
    noaa_swpc_l1_kafka
    noaa_swpc_l1_mqtt
    noaa_swpc_l1_amqp
    noaa_swpc_l1_producer/noaa_swpc_l1_producer_data/src
    noaa_swpc_l1_producer/noaa_swpc_l1_producer_kafka_producer/src
    noaa_swpc_l1_mqtt_producer/noaa_swpc_l1_mqtt_producer_data/src
    noaa_swpc_l1_mqtt_producer/noaa_swpc_l1_mqtt_producer_mqtt_client/src
    noaa_swpc_l1_amqp_producer/noaa_swpc_l1_amqp_producer_data/src
    noaa_swpc_l1_amqp_producer/noaa_swpc_l1_amqp_producer_amqp_producer/src
testpaths = tests
markers =
    unit: unit tests
