# Regenerate the MQTT producer (mqttclient style) from the authoritative
# xreg manifest. The companion Kafka producer is regenerated by
# generate_producer.ps1.

. (Join-Path $PSScriptRoot "..\tools\require-xrcg.ps1")
Assert-XrcgVersion

xrcg generate `
    --style mqttclient `
    --language py `
    --definitions xreg\wallonia_issep.xreg.json `
    --endpoint be.issep.airquality.Sensors.Mqtt `
    --projectname wallonia_issep_mqtt_producer `
    --output wallonia_issep_mqtt_producer
