# Regenerate the MQTT producer (mqttclient style) from the authoritative
# xreg manifest. The companion Kafka producer is regenerated by
# generate_producer.ps1.

. (Join-Path $PSScriptRoot "..\tools\require-xrcg.ps1")
Assert-XrcgVersion

xrcg generate `
    --style mqttclient `
    --language py `
    --definitions xreg\german_waters.xreg.json `
    --endpoint DE.Waters.Hydrology.Mqtt `
    --projectname german_waters_mqtt_producer `
    --output german_waters_mqtt_producer
