[build-system]
requires = ["poetry-core>=1.1.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "rssbridge"
version = "0.1.0"
description = "A project to fetch data from RSS feeds and publish them as CloudEvents"
authors = ["Clemens Vasters <clemensv@microsoft.com>"]


[tool.poetry.dependencies]
rssbridge_producer_data = {path = "rssbridge_producer/rssbridge_producer_data"}
rssbridge_producer_kafka_producer = {path = "rssbridge_producer/rssbridge_producer_kafka_producer"}
python = ">=3.8"
requests = ">=2.32.3"
confluent-kafka = ">=2.5.3"
cloudevents = ">=1.11.0"
dataclasses = ">=0.6"
dataclasses_json = ">=0.6.7"
feedparser = ">=6.0.11"
listparser = ">=0.20"
BeautifulSoup4 = ">=4.12.3"

[tool.poetry.dev-dependencies]
pytest = ">=8.3.3"
pytest-cov = ">=5.0.0"
testcontainers = ">=4.8.1"
requests-mock = ">=1.12.1"

[tool.poetry.scripts]
rssbridge = "rssbridge:main"
