# Regenerate the MQTT producer (mqttclient style) from the authoritative
# xreg manifest. The companion Kafka producer is regenerated by
# generate_producer.ps1.

. (Join-Path $PSScriptRoot "..\tools\require-xrcg.ps1")
Assert-XrcgVersion

xrcg generate `
    --style mqttclient `
    --language py `
    --definitions xreg\rws_waterwebservices.xreg.json `
    --endpoint NL.RWS.Waterwebservices.Mqtt `
    --projectname rws_waterwebservices_mqtt_producer `
    --output rws_waterwebservices_mqtt_producer
