# Regenerate the MQTT producer (mqttclient style) from the authoritative
# xreg manifest. The companion Kafka producer is regenerated by
# generate_producer.ps1.

. (Join-Path $PSScriptRoot "..\..\tools\require-xrcg.ps1")
Assert-XrcgVersion

xrcg generate `
    --style mqttclient `
    --language py `
    --definitions xreg\smhi-hydro.xreg.json `
    --endpoint SE.Gov.SMHI.Hydro.Mqtt `
    --projectname smhi_hydro_mqtt_producer `
    --output smhi_hydro_mqtt_producer
